theme: jekyll-theme-slate

title: Інформаційна система управління графіків та змін персоналу
description: Кваліфікаційна робота фахового молодшого бакалавра (ВСП «ППФК НТУ «ХПІ»)
author: Еліна Богомаз
